modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"

[[mods]]
modId="feywild"
version="${file.jarVersion}"
displayName="Feywild"
logoFile="feywild_mod_logo.png"
credits="Thanks to the Feywild community, with special thanks to HepheastusHammer, Kaupenjoe and DerringerCubed."
authors="Saphie & Playelectro"
description="Feywild Mod"

[[dependencies.feywild]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.feywild]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.feywild]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16.4-50,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.feywild]]
    modId="geckolib3"
    mandatory=true
    versionRange="[geckolib-forge-1.16.5:3.0.33,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.feywild]]
    modId="libx"
    mandatory=true
    versionRange="[1.16.3-1.0.76,)"
    ordering="NONE"
    side="BOTH"
